# The arena props, one row each. This is the ONLY place the scale lives.
#
#   "<vendor dir>  <scale>  <z offset, m>  <y offset, m>"
#
# <scale> is written verbatim into BOTH the visual and the collision <mesh><scale>
# of the generated model, from this one variable - so they cannot drift apart. That
# matters more than it looks: gz-sim's gpu_lidar and camera are RENDERING sensors and
# ray-cast against visuals, while the planner collides with collisions. A mismatch
# makes the LiDAR see one arena and the planner hit another, and nothing logs it.
#
# <scale> is the TOTAL scale, including whatever the upstream SDF already applied:
#   construction_barrel  upstream 1  x 0.18  = 0.18
#   jersey_barrier       upstream 1  x 0.18  = 0.18
#   construction_cone    upstream 10 x 0.25  = 2.50   <-- NOT 0.25
# The cone is the trap. Its upstream model.sdf ships <scale>10 10 10</scale>, so the
# raw mesh is a tenth of its nominal size and writing 0.25 here would give a 12 mm
# cone. props/<dir>/upstream_scale.txt records what upstream applied.
#
# Every number below is measured, not chosen by eye - props/<dir>/AABB.md and
# measured.json are generated by tools/dae_measure.py and committed. Scales were
# picked so each prop spans the whole mandated 80-180 mm LiDAR scan band
# (DOCK_PLAN.md 3.3) while staying under the 300 mm arena wall:
#
#   prop                 size (mm)              at z=145 mm    returns @1m / @4m
#   construction_barrel  184 x 184 x 279         99 x 99        7.1 / 1.8
#   jersey_barrier       732 x 146 x 206        732 x 63       52.4 / 13.1
#   construction_cone    126 x 126 x 272         59 x 59        4.2 / 1.1
#
# The cone is a deliberately weak LiDAR landmark - under 2 returns past 4 m, which is
# below the 3 needed to fit anything - and is carried for its orange/white diffuse
# map, i.e. as a CAMERA feature. The barrel and the barrier do the LiDAR work.
#
# The offsets put each mesh's measured min-z on the floor and its footprint on its own
# origin. All three of these assets are already authored that way, so all three are
# zero; they are not zero for every Fuel asset (Construction Barrel's rejected
# sibling, the NIST fiducial barrel, has its content 300 mm above its own origin).
# If you change a scale here, re-run tools/dae_measure.py and check the new
# origin_offset_mm - nothing checks this automatically any more.
set(PROP_ASSIGNMENTS
  "construction_barrel  0.18  0.0  0.0"
  "jersey_barrier       0.18  0.0  0.0"
  "construction_cone    2.50  0.0  0.0"
)
